name       : kdnssd
version    : 5.74.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kdnssd-5.74.0.tar.xz : 5c07b6dbe07ca994fcae084af0a9c2703d1450ad52d371be09cc849ba5f40cd0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.library
optimize   : lto
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
