name       : kdnssd
version    : 5.81.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kdnssd-5.81.0.tar.xz : 316e53ad258a08acff886a11a1f0fac69433a5df90b8c6ad5dea945c0a4f84c2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
component  : programming.library
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(avahi-core)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
