name       : kdnssd
version    : 5.85.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kdnssd-5.85.0.tar.xz : 1575b34bdd1fae9b2406ecc162e239d97128b6d143e3c82b028b362db1d93844
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
component  : programming.library
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(avahi-core)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
