name       : kdnssd
version    : 5.106.0
release    : 65
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/kdnssd-5.106.0.tar.xz : 117617da7700e5865ee044631f9ea818e49adf3e7a924aca96f3dc197a4ce8bb
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
component  : programming.library
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(avahi-core)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
