name       : kdnssd
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/kdnssd-5.36.0.tar.xz : 57504b89b327e0c4439c1be8037e13aba588155d5201adb3e81a1b52f8e28e1e
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
