name       : kdnssd
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/kdnssd-5.32.0.tar.xz : 3ccbd8cee0a72905cecaed02bf08978576627ef60e451b80fd4798ca855e53f5
license    :
    - BSD-3-Clause
    - LGPL-2.1
component  : programming
summary    : Network service discovery using Zeroconf
description: |
    KDNSSD is a library for handling the DNS-based Service Discovery Protocol (DNS-SD), the layer of Zeroconf that allows network services, such as printers, to be discovered without any user intervention or centralized infrastructure.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
